FROM hashbash-maven_build:current AS artifacts

FROM java:8-jre
MAINTAINER John Norwood <norwood.john.m@gmail.com>

ARG VERSION
ARG MODULE=webapp

WORKDIR /var/lib/johnmalcolmnorwood/hashbash
COPY --from=artifacts /opt/build/${MODULE}/target/hashbash-${MODULE}-${VERSION}.jar /var/lib/johnmalcolmnorwood/hashbash/hashbash-${MODULE}.jar

ENTRYPOINT ["java", "-jar", "hashbash-webapp.jar"]
