FROM java:8-jre

ARG VERSION
COPY webapp/target/hashbash-webapp-${VERSION}.jar /var/lib/johnmalcolmnorwood/hashbash/hashbash-webapp.jar
WORKDIR /var/lib/johnmalcolmnorwood/hashbash

ENTRYPOINT ["java", "-jar", "hashbash-webapp.jar"]
