##
# This stage of the build installs webpack and npm, and then builds a public dist archive out of our frontend code
##
FROM node:8.11.1-slim AS artifacts
MAINTAINER John Norwood <norwood.john.m@gmail.com>

ARG APP_DIR=/var/lib/johnmalcolmnorwood/hashbash
WORKDIR ${APP_DIR}

COPY web/package.json .
RUN npm install

COPY web/.babelrc .
COPY web/.eslintrc .
COPY web/webpack.config.js .
COPY web/src ./src

RUN node_modules/webpack/bin/webpack.js -p --progress


##
# This stage copies the generated dist archive from the previous stage of the build into the application home, and adds the
# nginx config file
##
FROM nginx:1.13.12
MAINTAINER John Norwood <norwood.john.m@gmail.com>

ARG APP_DIR=/var/lib/johnmalcolmnorwood/hashbash
WORKDIR ${APP_DIR}

COPY --from=artifacts ${APP_DIR}/dist ./dist
COPY etc/nginx/nginx.conf /etc/nginx/nginx.conf
