FROM hashbash-maven_build:current

FROM java:8-jre
MAINTAINER John Norwood <norwood.john.m@gmail.com>

ARG VERSION
WORKDIR /var/lib/johnmalcolmnorwood/hashbash
COPY --from=0 /opt/build/webapp/target/hashbash-webapp-${VERSION}.jar /var/lib/johnmalcolmnorwood/hashbash/hashbash-webapp.jar

ENTRYPOINT ["java", "-jar", "hashbash-webapp.jar"]
