FROM hashbash-rpi_maven_build:current

FROM jnorwood/rpi-java:1.8
MAINTAINER John Norwood <norwood.john.m@gmail.com>

ARG VERSION
ARG MODULE=engine

WORKDIR /var/lib/johnmalcolmnorwood/hashbash
COPY --from=0 /opt/build/${MODULE}/target/hashbash-${MODULE}-${VERSION}.jar /var/lib/johnmalcolmnorwood/hashbash/hashbash-${MODULE}.jar

ENTRYPOINT ["java", "-jar", "hashbash-engine.jar"]
